### ISSUE TITLE
Fix 'e' values on the diameters of some pads

### ISSUE THREAD

**Issue by Igor-Gold** [capablemonkey/odb-pp-parser#2] opened 2016-12-29 20:00 UTC
Some pads have a value of 'e' instead of a number for the diameter of the `round` shape.

If it's a variable or constant, I think we should decisively assign it a value, just to make things simple for now.

**Comment by capablemonkey** [comment] 2016-12-30 16:01
Looks like the problem is that the regex being used to detect the `round` symbol is also matching `rect38x30`.

`rect38x30` matches `r(?<diameter>\d*(.?\d*))`

Gonna constrain the regexes a bit more.  Maybe now's a good time to add tests :)

**Comment by Igor-Gold** [comment] 2016-12-30 18:40
Writing tests shows lack of confidence in your own code

Have faith! Believe in yourself

**Comment by capablemonkey** [comment] 2016-12-30 22:16
Wow.  You should talk more about this in a Medium post.

**Comment by capablemonkey** [comment] 2016-12-30 22:16
And then use that as a slogan for your resume.

**Comment by capablemonkey** [comment] 2016-12-30 22:17
Development practices: TDD / BDD / FDD (Faith Driven Development)

**Comment by capablemonkey** [comment] 2016-12-30 22:20
"I bring efficiency to teams by coaching Faith Driven Development (FDD), saving 500%+ time and project cost by replacing unit tests with brief, daily prayer."

**Comment by capablemonkey** [comment] 2016-12-30 22:30
Fixed by https://github.com/capablemonkey/odb-pp-parser/commit/f5bb3a5567215f13bcf52ef6446e09e60b847c96

**Closed as completed by capablemonkey** 2016-12-30 22:30 UTC
